import jsPDF from "jspdf";

const generatePdf = (
  user,
  category,
  score,
  total
) => {
  try {
    const doc = new jsPDF();

    const percentage =
      total > 0
        ? (
            (score / total) *
            100
          ).toFixed(0)
        : 0;

    const result =
      percentage >= 50
        ? "PASSED"
        : "FAILED";

    // ==========================
    // BORDER
    // ==========================

    doc.rect(
      10,
      10,
      190,
      277
    );

    // ==========================
    // HEADER
    // ==========================

    doc.setFontSize(24);
    doc.setFont(
      "helvetica",
      "bold"
    );

    doc.text(
      "QUIZ MASTER",
      70,
      25
    );

    doc.setFontSize(18);

    doc.text(
      "Quiz Result Report",
      60,
      38
    );

    // Line
    doc.line(
      20,
      45,
      190,
      45
    );

    // ==========================
    // STUDENT DETAILS
    // ==========================

    doc.setFontSize(14);

    doc.setFont(
      "helvetica",
      "bold"
    );

    doc.text(
      "Student Information",
      20,
      60
    );

    doc.setFont(
      "helvetica",
      "normal"
    );

    doc.text(
      `Name: ${
        user?.name ||
        "Guest"
      }`,
      20,
      75
    );

    doc.text(
      `Email: ${
        user?.email ||
        "N/A"
      }`,
      20,
      85
    );

    // ==========================
    // QUIZ DETAILS
    // ==========================

    doc.setFont(
      "helvetica",
      "bold"
    );

    doc.text(
      "Quiz Details",
      20,
      105
    );

    doc.setFont(
      "helvetica",
      "normal"
    );

    doc.text(
      `Category: ${category}`,
      20,
      120
    );

    doc.text(
      `Score: ${score}/${total}`,
      20,
      130
    );

    doc.text(
      `Percentage: ${percentage}%`,
      20,
      140
    );

    doc.text(
      `Date: ${new Date().toLocaleDateString()}`,
      20,
      150
    );

    // ==========================
    // RESULT BOX
    // ==========================

    doc.setDrawColor(
      0,
      0,
      0
    );

    doc.rect(
      120,
      110,
      60,
      35
    );

    doc.setFontSize(18);

    doc.setFont(
      "helvetica",
      "bold"
    );

    doc.text(
      result,
      135,
      132
    );

    // ==========================
    // PERFORMANCE MESSAGE
    // ==========================

    doc.setFontSize(14);

    doc.text(
      percentage >= 50
        ? "Congratulations! You have successfully completed the quiz."
        : "Keep practicing and try again for a better score.",
      20,
      180
    );

    // ==========================
    // SIGNATURE
    // ==========================

    doc.line(
      130,
      240,
      180,
      240
    );

    doc.text(
      "Quiz Master",
      140,
      250
    );

    doc.text(
      "Authorized Signature",
      125,
      258
    );

    // ==========================
    // FOOTER
    // ==========================

    doc.setFontSize(10);

    doc.text(
      "Generated by Quiz Master Learning Platform",
      20,
      275
    );

    // ==========================
    // DOWNLOAD
    // ==========================

    doc.save(
      `${category}-Quiz-Result.pdf`
    );
  } catch (error) {
    console.error(
      "PDF Generation Error:",
      error
    );

    alert(
      "Unable to generate PDF."
    );
  }
};

export default generatePdf;