import jsPDF from "jspdf";

const generatePdf = (
  user,
  category,
  score,
  total
) => {
  try {

    const doc =
      new jsPDF();

    const percentage =
      total > 0
        ? (
            (score / total) *
            100
          ).toFixed(0)
        : 0;

    const result =
      percentage >= 50
        ? "PASSED"
        : "FAILED";

    // -----------------------------
    // TITLE
    // -----------------------------

    doc.setFontSize(22);

    doc.text(
      "Quiz Master",
      20,
      25
    );

    doc.setFontSize(18);

    doc.text(
      "Quiz Result Report",
      20,
      38
    );

    // -----------------------------
    // STUDENT DETAILS
    // -----------------------------

    doc.setFontSize(12);

    doc.text(
      `Student Name: ${
        user?.name || "Guest"
      }`,
      20,
      58
    );

    doc.text(
      `Email: ${
        user?.email || "N/A"
      }`,
      20,
      68
    );

    // -----------------------------
    // QUIZ DETAILS
    // -----------------------------

    doc.text(
      `Quiz Category: ${category}`,
      20,
      82
    );

    doc.text(
      `Score: ${score}/${total}`,
      20,
      92
    );

    doc.text(
      `Percentage: ${percentage}%`,
      20,
      102
    );

    doc.text(
      `Result: ${result}`,
      20,
      112
    );

    doc.text(
      `Date: ${new Date().toLocaleDateString()}`,
      20,
      122
    );

    // -----------------------------
    // FOOTER
    // -----------------------------

    doc.setFontSize(10);

    doc.text(
      "Generated by Quiz Master",
      20,
      145
    );

    // -----------------------------
    // DOWNLOAD
    // -----------------------------

    doc.save(
      `${category}-Quiz-Result.pdf`
    );

  } catch (error) {

    console.error(
      "PDF Generation Error:",
      error
    );

    alert(
      "Unable to generate PDF."
    );
  }
};

export default generatePdf;